### ISSUE TITLE
@keyframe syntax

### ISSUE THREAD

**Issue by kevinresol** [back2dos/cix#18]
```css
@keyframes move {
  100% {
    transform: translate(200px, 0);
  }
}
```

Normal css does not has a colon after `100%`, but cix requires it. Is this intended?

**Comment by kevinresol** [comment]
Also, multi-declaration like the following is not supported in cix:
```css
@keyframes move {
  20%, 100% {
    transform: translate(200px, 0);
  }
}
```

**Comment by kevinresol** [comment]
And vendor keyframes is not supported, e.g. :

```css
@-webkit-keyframes NAME-YOUR-ANIMATION {
  0%   { opacity: 0; }
  100% { opacity: 1; }
}
```

**Comment by back2dos** [comment]
The colon is an oversight indeed.

As for vendor prefixes, it should be solved in the printer - both for keyframes and properties in general.

**Comment by kevinresol** [comment]
Currently cix expects identifier after "@", so vendor prefixes doesn't parse.

https://github.com/back2dos/cix/blob/a3c9f675ab1c384adaa5d1b9ed11e3214b3bdb88/src/cix/css/Parser.hx#L286-L287

**Comment by back2dos** [comment]
Uhm, what I meant is that you shouldn't have to be writing that in the first place. Instead, write `@keyframes` and then in [`printKeyFrames`](https://github.com/back2dos/cix/blob/a3c9f675ab1c384adaa5d1b9ed11e3214b3bdb88/src/cix/css/Printer.hx#L89) it should generate both versions if some define is set. 

Or do you intend to have an entirely different animation depending on whether the browser considers itself webkit-based?

**Comment by kevinresol** [comment]
Oh, I get it now.

But there are a few of them. Do we want to support all?

```css
-webkit-animation: walk .9s steps(6) infinite;
-moz-animation: walk .9s steps(6) infinite;
-ms-animation: walk .9s steps(6) infinite;
-o-animation: walk .9s steps(6) infinite;
@-webkit-keyframes walk {}
@-moz-keyframes walk {}
@-ms-keyframes walk {}
@-o-keyframes walk {}
```
